global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets:
          -  'jmxexporter-1:5556'
          -  'jmxexporter-2:5556'
          -  'jmxexporter-3:5556'