{
 "title": "Kafka Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Produce time, 99% time",
   "type": "timeseries",
   "description": "The total time taken to service requests from producers to send data.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{name=\"TotalTimeMs\",request=\"Produce\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Fetch consumer, 99% time",
   "type": "timeseries",
   "description": "The total time taken to service requests from consumers to get new data.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{name=\"TotalTimeMs\",request=\"FetchConsumer\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Fetch follower, 99% time",
   "type": "timeseries",
   "description": "The total time taken to service requests from brokers that are the followers of a partition to get new data.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{name=\"TotalTimeMs\",request=\"FetchFollower\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}